[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "radiocontrol"
version = "0.4.0"
description = "Radio command CLI"
requires-python = ">3.11"

[tool.setuptools]
package-dir = {"" = "src"}
py-modules = ["radiocontrol", "panwidget"]

[project.scripts]
p5 = "radiocontrol:p5"
p20 = "radiocontrol:p20"
p40 = "radiocontrol:p40"
p60 = "radiocontrol:p60"
p80 = "radiocontrol:p80"
p100 = "radiocontrol:p100"
pmax = "radiocontrol:pmax"
Scott = "radiocontrol:Scott"
NoScott = "radiocontrol:NoScott"
PCOff = "radiocontrol:pcoff"
PCON = "radiocontrol:pcon"
CapeCod = "radiocontrol:CapeCod"
Charlotte = "radiocontrol:Charlotte"
setCW = "radiocontrol:setCW"
test = "radiocontrol:test"
setdebug = "radiocontrol:setdebug"
unsetdebug = "radiocontrol:unsetdebug"
ft = "radiocontrol:ft"
panwidget = "panwidget:run"
t160c = "radiocontrol:t160c"
t160s = "radiocontrol:t160s"
t80c = "radiocontrol:t80c"
t80s = "radiocontrol:t80s"
t40c = "radiocontrol:t40c"
t40s = "radiocontrol:t40s"
t30c = "radiocontrol:t30c"
t20c = "radiocontrol:t20c"
t20s = "radiocontrol:t20s"
t17c = "radiocontrol:t17c"
t17s = "radiocontrol:t17s"
t15c = "radiocontrol:t15c"
t15s = "radiocontrol:t15s"
t12c = "radiocontrol:t12c"
t12s = "radiocontrol:t12s"
t10c = "radiocontrol:t10c"
t10s = "radiocontrol:t10s"